"""delete frequence

Revision ID: e340a4b2d7ed
Revises: 72b4b1ea4fca
Create Date: 2025-12-11 00:05:55.395419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e340a4b2d7ed'
down_revision: Union[str, None] = '72b4b1ea4fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
